# permissions for end users to edit awsgateways.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: awsgateway-editor-role
rules:
- apiGroups:
  - terraform.tmax.io
  resources:
  - awsgateways
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - terraform.tmax.io
  resources:
  - awsgateways/status
  verbs:
  - get
