# permissions for end users to view awsgateways.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: awsgateway-viewer-role
rules:
- apiGroups:
  - terraform.tmax.io
  resources:
  - awsgateways
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - terraform.tmax.io
  resources:
  - awsgateways/status
  verbs:
  - get
