# permissions for end users to edit awsinstances.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: awsinstance-editor-role
rules:
- apiGroups:
  - terraform.tmax.io
  resources:
  - awsinstances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - terraform.tmax.io
  resources:
  - awsinstances/status
  verbs:
  - get
