# permissions for end users to view awsinstances.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: awsinstance-viewer-role
rules:
- apiGroups:
  - terraform.tmax.io
  resources:
  - awsinstances
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - terraform.tmax.io
  resources:
  - awsinstances/status
  verbs:
  - get
