# permissions for end users to view awskeys.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: awskey-viewer-role
rules:
- apiGroups:
  - terraform.tmax.io
  resources:
  - awskeys
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - terraform.tmax.io
  resources:
  - awskeys/status
  verbs:
  - get
