# permissions for end users to edit awskeys.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: awskey-editor-role
rules:
- apiGroups:
  - terraform.tmax.io
  resources:
  - awskeys
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - terraform.tmax.io
  resources:
  - awskeys/status
  verbs:
  - get
