# permissions for end users to edit awsroutes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: awsroute-editor-role
rules:
- apiGroups:
  - terraform.tmax.io
  resources:
  - awsroutes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - terraform.tmax.io
  resources:
  - awsroutes/status
  verbs:
  - get
