# permissions for end users to view awsroutes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: awsroute-viewer-role
rules:
- apiGroups:
  - terraform.tmax.io
  resources:
  - awsroutes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - terraform.tmax.io
  resources:
  - awsroutes/status
  verbs:
  - get
