# permissions for end users to view awssecuritygroups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: awssecuritygroup-viewer-role
rules:
- apiGroups:
  - terraform.tmax.io
  resources:
  - awssecuritygroups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - terraform.tmax.io
  resources:
  - awssecuritygroups/status
  verbs:
  - get
