# permissions for end users to edit awssecuritygrouprules.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: awssecuritygrouprule-editor-role
rules:
- apiGroups:
  - terraform.tmax.io
  resources:
  - awssecuritygrouprules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - terraform.tmax.io
  resources:
  - awssecuritygrouprules/status
  verbs:
  - get
