# permissions for end users to edit awssecuritygroups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: awssecuritygroup-editor-role
rules:
- apiGroups:
  - terraform.tmax.io
  resources:
  - awssecuritygroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - terraform.tmax.io
  resources:
  - awssecuritygroups/status
  verbs:
  - get
