# permissions for end users to edit awssubnets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: awssubnet-editor-role
rules:
- apiGroups:
  - terraform.tmax.io
  resources:
  - awssubnets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - terraform.tmax.io
  resources:
  - awssubnets/status
  verbs:
  - get
