# permissions for end users to view awsvpcs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: awsvpc-viewer-role
rules:
- apiGroups:
  - terraform.tmax.io
  resources:
  - awsvpcs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - terraform.tmax.io
  resources:
  - awsvpcs/status
  verbs:
  - get
