# permissions for end users to edit hcls.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hcl-editor-role
rules:
- apiGroups:
  - terraform.tmax.io
  resources:
  - hcls
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - terraform.tmax.io
  resources:
  - hcls/status
  verbs:
  - get
