# permissions for end users to edit securities.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: security-editor-role
rules:
- apiGroups:
  - terraform.tmax.io
  resources:
  - securities
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - terraform.tmax.io
  resources:
  - securities/status
  verbs:
  - get
