# permissions for end users to view tfapplyclaims.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tfapplyclaim-viewer-role
rules:
- apiGroups:
  - claim.tmax.io
  resources:
  - tfapplyclaims
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - claim.tmax.io
  resources:
  - tfapplyclaims/status
  verbs:
  - get
